PSG-6669: switch / for - in content types
Congenica/psga-pipeline pull request #318
Opened 2024-09-05 14:32 UTC by cramshaw

2024-09-05 15:46 UTC, congenica-peter-fox requested changes

2024-09-05 15:46 UTC, congenica-peter-fox commented on app/config/psga-schema-sars-cov-2.yaml
> +            reprocessing_content_type: fastq-cleaned-sequence-data
Although you've fixed reprocessing_content_type you didn't fix content_type

2024-09-06 09:04 UTC, cramshaw commented on app/config/psga-schema-sars-cov-2.yaml
> +            reprocessing_content_type: fastq-cleaned-sequence-data
updated

2024-09-06 10:49 UTC, congenica-peter-fox approved these changes

2024-09-06 10:52 UTC, merged